-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Tiny.

module Tiny.Syntax.PrintSyntax where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Tiny.Syntax.AbsSyntax
import qualified Data.Text

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Tiny.Syntax.AbsSyntax.VarIdent where
  prt _ (Tiny.Syntax.AbsSyntax.VarIdent i) = doc $ showString (Data.Text.unpack i)
instance Print Tiny.Syntax.AbsSyntax.Expr where
  prt i = \case
    Tiny.Syntax.AbsSyntax.ExprVar varident -> prPrec i 0 (concatD [prt 0 varident])
    Tiny.Syntax.AbsSyntax.ExprConst n -> prPrec i 0 (concatD [prt 0 n])
    Tiny.Syntax.AbsSyntax.ExprOp expr1 intop expr2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 expr1, prt 0 intop, prt 0 expr2, doc (showString ")")])

instance Print Tiny.Syntax.AbsSyntax.IntOp where
  prt i = \case
    Tiny.Syntax.AbsSyntax.Plus -> prPrec i 0 (concatD [doc (showString "+")])
    Tiny.Syntax.AbsSyntax.Minus -> prPrec i 0 (concatD [doc (showString "-")])
    Tiny.Syntax.AbsSyntax.Multiply -> prPrec i 0 (concatD [doc (showString "*")])
    Tiny.Syntax.AbsSyntax.Div -> prPrec i 0 (concatD [doc (showString "/")])
    Tiny.Syntax.AbsSyntax.Mod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print Tiny.Syntax.AbsSyntax.IntCondOp where
  prt i = \case
    Tiny.Syntax.AbsSyntax.Eq -> prPrec i 0 (concatD [doc (showString "=")])
    Tiny.Syntax.AbsSyntax.NotEq -> prPrec i 0 (concatD [doc (showString "/=")])
    Tiny.Syntax.AbsSyntax.Gt -> prPrec i 0 (concatD [doc (showString ">")])
    Tiny.Syntax.AbsSyntax.GtEq -> prPrec i 0 (concatD [doc (showString ">=")])
    Tiny.Syntax.AbsSyntax.Lt -> prPrec i 0 (concatD [doc (showString "<")])
    Tiny.Syntax.AbsSyntax.LtEq -> prPrec i 0 (concatD [doc (showString "<=")])

instance Print Tiny.Syntax.AbsSyntax.BoolCondOp where
  prt i = \case
    Tiny.Syntax.AbsSyntax.Or -> prPrec i 0 (concatD [doc (showString "||")])
    Tiny.Syntax.AbsSyntax.And -> prPrec i 0 (concatD [doc (showString "&&")])

instance Print Tiny.Syntax.AbsSyntax.Cond where
  prt i = \case
    Tiny.Syntax.AbsSyntax.IntCond expr1 intcondop expr2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 expr1, prt 0 intcondop, prt 0 expr2, doc (showString ")")])
    Tiny.Syntax.AbsSyntax.BoolCond cond1 boolcondop cond2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 cond1, prt 0 boolcondop, prt 0 cond2, doc (showString ")")])
    Tiny.Syntax.AbsSyntax.NotCond cond -> prPrec i 0 (concatD [doc (showString "("), doc (showString "!"), prt 0 cond, doc (showString ")")])

instance Print Tiny.Syntax.AbsSyntax.Annotatation where
  prt i = \case
    Tiny.Syntax.AbsSyntax.Annotatation cond -> prPrec i 0 (concatD [doc (showString "annotate"), doc (showString "with"), prt 0 cond])

instance Print [Tiny.Syntax.AbsSyntax.Statement] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print Tiny.Syntax.AbsSyntax.Statement where
  prt i = \case
    Tiny.Syntax.AbsSyntax.Assign varident expr -> prPrec i 0 (concatD [prt 0 varident, doc (showString ":="), prt 0 expr])
    Tiny.Syntax.AbsSyntax.Composition statements -> prPrec i 0 (concatD [doc (showString "("), prt 0 statements, doc (showString ")")])
    Tiny.Syntax.AbsSyntax.While annotatation cond statement -> prPrec i 0 (concatD [prt 0 annotatation, doc (showString "while"), prt 0 cond, doc (showString "do"), prt 0 statement])
